# TerraformPlan.yml - GitHub Actions workflow for Terraform GitOps via GitHub App v3 Pull Requests & Check Runs

name: 'Terraform Plan'

on:
  pull_request:
    types: [opened, reopened, synchronize]
  check_run:
    types: rerequested

env:
  tf_version: 'latest'
  tf_directory: '.'

jobs:
  terraform:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
        
      - name: 'Terraform Init'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: 'init'
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_working_dir: ${{ env.tf_directory }}
          tf_actions_comment: true

      - name: 'Terraform Plan'
        uses: hashicorp/terraform-github-actions@master
        with:
          tf_actions_subcommand: 'plan'
          tf_actions_version: ${{ env.tf_version }}
          tf_actions_working_dir: ${{ env.tf_directory }}
          tf_actions_comment: true
